[build]
  publish = "."
  functions = "functions"

[build.environment]
  MONGODB_URI = "mongodb+srv://Leoly:Bangsat88@leoly.9rhahjy.mongodb.net/"
  MONGODB_DB = "leoly_portfolio"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"